import { useEffect, useState } from 'react'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import MeetUpList from '../components/meetups/MeetupList'
import Layout from '../components/layout' 
import MainNavigation  from '../components/layout/MainNavigation'

// our-domain.com/

const DUMMY_MEETUPS = [
  {
      id: 'm1',
      title: 'Meetup 1',
      image: 'https://en.wikipedia.org/wiki/Eiffel_Tower#/media/File:Tour_Eiffel_Wikimedia_Commons.jpg',
      address: 'Address 1'
  },
  {
    id: 'm2',
    title: 'Meetup 2',
    image: 'https://en.wikipedia.org/wiki/Eiffel_Tower#/media/File:Tour_Eiffel_Wikimedia_Commons.jpg',
    address: 'Address 2'
  },
  {
    id: 'm3',
    title: 'Meetup 3',
    image: 'https://en.wikipedia.org/wiki/Eiffel_Tower#/media/File:Tour_Eiffel_Wikimedia_Commons.jpg',
    address: 'Address 3'
  },
  {
    id: 'm4',
    title: 'Meetup 4',
    image: 'https://en.wikipedia.org/wiki/Eiffel_Tower#/media/File:Tour_Eiffel_Wikimedia_Commons.jpg',
    address: 'Address 4'
  }

]

export default function Main() {
  const [loadedMeetups, setloadedMeetups ] = useState([])
  useEffect(() => {
    setloadedMeetups(DUMMY_MEETUPS)
  }, [])
  return (
    <div className={styles.container}>
        <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout><MeetUpList meetups={loadedMeetups}/></Layout>
       
     
    </div>
    
  )
}

 async function getStaticProps(){
  // fetch data from an API
  return {
    props: {
      meetups: DUMMY_MEETUPS
    }
  }
}
