import Head from 'next/head'
import NavBar from '../components/Navbar'
import styles from '../styles/Home.module.css'
import MeetUpList from '../components/meetups/MeetupList'
// our-domain.com/

const DUMMY_MEETUPS = [
  {
      id: 'm1',
      title: 'Meetup 1',
      image: 'https://en.wikipedia.org/wiki/Eiffel_Tower#/media/File:Tour_Eiffel_Wikimedia_Commons.jpg',
      address: 'Address 1'
  },
  {
    id: 'm2',
    title: 'Meetup 2',
    image: 'https://en.wikipedia.org/wiki/Eiffel_Tower#/media/File:Tour_Eiffel_Wikimedia_Commons.jpg',
    address: 'Address 2'
  },
  {
    id: 'm3',
    title: 'Meetup 3',
    image: 'https://en.wikipedia.org/wiki/Eiffel_Tower#/media/File:Tour_Eiffel_Wikimedia_Commons.jpg',
    address: 'Address 3'
  },
  {
    id: 'm4',
    title: 'Meetup 4',
    image: 'https://en.wikipedia.org/wiki/Eiffel_Tower#/media/File:Tour_Eiffel_Wikimedia_Commons.jpg',
    address: 'Address 4'
  }

]

export default function Main() {

  return (
    <div className={styles.container}>
        <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <MeetUpList meetups={DUMMY_MEETUPS}/>
        <main className={styles.main}>
        <div><h1>Main</h1></div>
      </main>
      <footer className={styles.footer}>
        Footer
      </footer>
    </div>
    
  )
}

